# Config

NAME := "envy"
ENV := "development"
DATABASE_DIR := "db"
DATABASE_SCHEMA_DIR := "schema"

# Database

## Database - Private
db-name:
  @echo {{NAME}}-{{ENV}}
db-url:
  @turso db show $(just db-name) --url
db-create:
  turso db create $(just db-name)
db-token:
  @turso db tokens create $(just db-name)

## Database - Public

db-login:
  turso auth login
  atlas login
db-migrate:
  cd {{DATABASE_DIR}} && \
  atlas schema apply -u "$(just db-url)?authToken=$(just db-token)" \
  --to file://{{DATABASE_SCHEMA_DIR}} --exclude '_litestream_seq,_litestream_lock'
db-lint:
  cd {{DATABASE_DIR}} && \
  atlas migrate lint --dev-url "sqlite://dev?mode=memory" -w
db-diff:
  cd {{DATABASE_DIR}} && \
  atlas migrate diff --to file://{{DATABASE_SCHEMA_DIR}} --dev-url "sqlite://dev?mode=memory"
