[workspace]
resolver = "2"

members = [
    "packages/compiler",

    "packages/parser",
    "packages/parser/examples",

    "packages/lexer",
    "packages/lexer/examples",

    "packages/resolver",
    "packages/resolver/examples",

    "packages/language-server",

    "packages/code-generation/javascript",
    "packages/code-generation/javascript/examples",

    "packages/provider/core",

    "packages/provider/providers/env",
    "packages/provider/providers/env/examples",

    "packages/provider/providers/aws-secrets-manager",
    "packages/provider/providers/aws-secrets-manager/examples",
]
