[workspace]

members = [
    "packages/compiler",
    "packages/parser",
    "packages/lexer",

    "packages/code-generation/wasm",
    
    "packages/language-server",

    "examples/lexer-api",
    "examples/parser-api",
]
