[package]
name = "load-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
charming = { version = "0.3.1", features = ["ssr"] }
env_logger = "0.11.3"
log = "0.4.21"
nv-provider-core = { path = "../lib" }
tokio = { version = "1.37.0", features = ["rt", "time"] }
