[package]
name = "envy-examples-var-resolver-api"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.2"
log = "0.4.20"
envy-parser = { path = "../../../parser/lib" }
envy-lexer = { path = "../../../lexer/lib" }
envy-var-resolver = { path = "../../var/lib" }
envy-provider-resolver = { path = "../../provider/lib" }
envy-provider-env = { path = "../../../providers/env/lib" }
envy-provider-aws-secrets-manager = { path = "../../../providers/aws-secrets-manager/lib" }
futures = "0.3.30"
