[package]
name = "nv-examples-codegen-javascript"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.2"
log = "0.4.20"
nv-codegen-javascript = { path = "../" }
nv-parser = { path = "../../../parser" }
