[package]
name = "nv-language-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
env_logger = "0.11.3"
log = "0.4.21"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = [
  "io-util",
  "rt-multi-thread",
  "macros",
  "net",
] }
nv-parser = { path = "../parser" }
nv-lexer = { path = "../lexer" }
nv-position-indexer = { path = "../position_indexer" }
nv-var-resolver = { path = "../resolvers/var" }
