[package]
name = "nv-language-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
env_logger = "0.11.3"
log = "0.4.21"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["io-util", "rt-multi-thread", "macros", "net"] }
nv-parser = { path = "../parser" }