[package]
name = "envy-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["cargo", "derive"] }
envy-parser = { path = "../parser/lib" }
envy-lexer = { path = "../lexer/lib" }
envy-var-resolver = { path = "../resolvers/var/lib" }
envy-provider-resolver = { path = "../resolvers/provider/lib" }
envy-provider-env = { path = "../providers/env/lib" }
envy-provider-aws-secrets-manager = { path = "../providers/aws-secrets-manager/lib" }
tokio = { version = "1.39.2", features = ["rt-multi-thread", "macros"] }
log = "0.4.22"
env_logger = "0.11.5"
