[package]
name = "nv-provider-aws-secrets-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
nv-provider-core = { path = "../../core" }
aws-config = { version = "1.1.8", features = ["behavior-version-latest"] }
aws-sdk-secretsmanager = "1.19.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
async-trait = "0.1.79"
